default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 15) %>

development:
  <<: *default
  database: docuseal_dev

test:
  <<: *default
  database: docuseal_test

production:
  <<: *default
  adapter: utf8mb4
  host: 10.102.9.53
  encoding: utf8
  database: sign
  username: sign
  password: 8Ph79Pge5u5DBh
